# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='life',
            field=models.IntegerField(default=1),
        ),
    ]
