# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_rain'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(default=13.562975),
        ),
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.FloatField(default=80.021457),
        ),
    ]
